#!/usr/bin/env python3
"""Ingest raw static-analysis tool output into panopticon findings.

Files in *tools_dir* are matched by basename (without extension) against the
registered adapters in ``scripts.tools.ADAPTERS`` and routed to the matching
adapter for parsing. SARIF or JSON files whose basename has no registered
adapter are skipped with a diagnostic. Stdlib-only.
"""
import fnmatch
import glob
import os
import sys

from scripts.tools import ADAPTERS
from scripts.tools.base import strip_ansi
from scripts.tools.sarif_utils import (
    CWE_TAG,
    CVE_TAG,
    LEVEL_TO_SEV,
    NOISE_RULES,
    PREFIX,
    is_fixture_path,
    is_test_path,
    norm_uri,
    rules_index,
    _is_fixture_path,
    _is_test_path,
    _norm_uri,
    _rules_index,
    sarif_to_findings,
)
from scripts.run_tools import MAX_TOOL_OUTPUT_BYTES  # #run7 OPS-D1A: shared cap

# Re-export shared SARIF helpers so existing callers/tests keep working.
__all__ = [
    "CWE_TAG",
    "CVE_TAG",
    "LEVEL_TO_SEV",
    "NOISE_RULES",
    "PREFIX",
    "is_fixture_path",
    "is_test_path",
    "norm_uri",
    "rules_index",
    "_is_fixture_path",
    "_is_test_path",
    "_norm_uri",
    "_rules_index",
    "ingest_dir",
    "ingest_dir_detailed",
    "sarif_to_findings",
]


# Top-level dirs that are never project source: a nested checkout, the git dir,
# and panopticon's OWN artifact tree.
_RUN_ARTIFACT_DIRS = {".worktrees", ".git", ".panopticon"}
# Dirs that are generated build output at ANY depth, plus their file extensions.
_GENERATED_DIRS = {"__pycache__"}
_GENERATED_SUFFIXES = (".pyc", ".pyo")
# VENDORED third-party dependencies at any depth. Same class as generated
# bytecode: present in the tree, scanned by every tool, and not the project's
# code to fix. #calibration-5 (solidus) -- eslint-security emitted 623 messages
# and 592 of them (95%) were in `vendor/`, almost all one rule
# (security/detect-object-injection) firing on bundled jQuery and friends.
# Deliberately conservative: only the conventional dependency directories, and
# only as a PATH SEGMENT, so a project file named `vendor_test.rb` or a
# legitimate `app/vendors/` model is untouched.
_VENDORED_DIRS = {"vendor", "node_modules", "bower_components", "third_party",
                  "vendored", ".bundle", ".yarn"}


def _is_run_artifact_path(fpath):
    """True for a tool finding located in something that is not project source.

    run_tools mounts the whole target read-only and the scanners walk ALL of it,
    while the agentic scan prunes these -- so the tool path re-finds what review
    never looks at. Three classes, all unconditional (unlike the fixture prune,
    which has an include_fixtures opt-in):

    - a NESTED CHECKOUT (`.worktrees/`) or the git dir -- run-9 E3.
    - `.panopticon/` -- panopticon's OWN artifact tree. run-10 D1: gitleaks
      flagged `private-key` inside
      `.panopticon/claude-redteam-repo-20260825-...-report-discarded.json`, i.e.
      THIS run re-found the rejected secret findings of a PREVIOUS run, and
      semgrep flagged the run's own `tools/gitleaks.sarif`. Every run left
      artifacts for the next run to re-adjudicate, so tool-axis noise compounded
      run over run instead of staying flat.
    - GENERATED bytecode (`__pycache__/`, `*.pyc`) at any depth -- a finding
      "in" compiled bytecode is unactionable and duplicates its own source file.
    - VENDORED dependencies (`vendor/`, `node_modules/`, ...) at any depth --
      #calibration-5 (solidus). Third-party code the project ships but does not
      author: a finding there is not the project's to fix, and the dependency
      scanners (osv-scanner, trivy, bundler-audit) already cover that surface by
      VERSION, which is the actionable form. eslint-security emitted 623
      messages on solidus and 592 of them (95%) were in `vendor/`.

    Together the first three were 16 of run-10's 54 rejected tool findings
    (30%), each one costing a tool-advisor dispatch to reject.
    """
    norm = str(fpath).replace(os.sep, "/").lstrip("/")
    parts = norm.split("/")
    if parts[0] in _RUN_ARTIFACT_DIRS:
        return True
    if any(p in _GENERATED_DIRS for p in parts[:-1]):
        return True
    if any(p in _VENDORED_DIRS for p in parts[:-1]):
        return True
    return norm.endswith(_GENERATED_SUFFIXES)


def _filter_parsed_findings(parsed, include_fixtures, exclude_globs):
    kept, fx_count, gl_count, ra_count = [], 0, 0, 0
    for f in parsed:
        # #run7 QAL-D1A: normalize os.sep -> "/" before matching, mirroring
        # run_tools._is_excluded, so an exclude_glob behaves identically on both
        # the ingest and the scan path (a no-op on POSIX; correct on Windows).
        fpath = str((f.get("location") or {}).get("file", "")).replace(os.sep, "/")
        if _is_run_artifact_path(fpath):      # run-9 E3 / run-10 D1: not project source
            ra_count += 1
        elif not include_fixtures and _is_fixture_path(fpath):
            fx_count += 1
        elif exclude_globs and any(fnmatch.fnmatch(fpath, g) for g in exclude_globs):
            gl_count += 1
        else:
            kept.append(f)
    return kept, fx_count, gl_count, ra_count


def ingest_dir_detailed(tools_dir, group, exclude_globs=None, include_fixtures=False):
    """Ingest raw tool-output files and report each adapter's disposition.

    Returns (findings, dispositions). dispositions maps each output file's
    adapter name (its filename stem) to {"status": ok|empty|failed,
    "findings": int} plus a "reason" when failed. This is the single
    authoritative walk — a file's disposition reflects exactly what parsing
    saw, so nothing downstream can classify it differently. `findings` is the
    adapter's raw yield BEFORE fixture exclusion, so an adapter whose findings
    were all fixture-noise still reads as having run (status/findings from the
    raw parse; only `out` is filtered).

    Fixture prune (default): unless *include_fixtures* is True, findings whose
    location.file lives under a test-fixture corpus dir (``_is_fixture_path``)
    are dropped — the tool-path equivalent of the agentic review-path prune
    (#434). The tool scanners (osv-scanner, trivy) walk the whole repo and
    report the intentionally-vulnerable fixtures under tests/fixtures/, which
    would otherwise dominate a self-scan. #1055: the prune is keyed on the
    explicit include_fixtures flag alone — redteam no longer auto-keeps fixture
    TOOL findings (that only re-adjudicated designed-vulnerable scaffolding);
    pass include_fixtures=True to opt in. Fixture CONTENT review is independent
    of this flag (it is governed by groups.yml routing on the review path).

    exclude_globs (F-CAL-2): additional fnmatch patterns matched against each
    finding's location.file; matches are dropped too. Both filters share one
    aggregate stderr note.
    """
    out = []
    dispositions = {}
    fx_excluded = 0   # dropped by the default fixture-corpus prune
    gl_excluded = 0   # dropped by an explicit exclude_glob
    ra_excluded = 0   # dropped as not-project-source (run-9 E3 / run-10 D1)
    for path in sorted(glob.glob(os.path.join(tools_dir, "*.sarif"))
                       + glob.glob(os.path.join(tools_dir, "*.json"))):
        tool = os.path.splitext(os.path.basename(path))[0]
        adapter = ADAPTERS.get(tool)
        if adapter is None:
            print("ingest skip %s: no adapter registered" % path, file=sys.stderr)
            dispositions[tool] = {"status": "failed", "findings": 0,
                                  "reason": "no registered adapter"}
            continue
        try:
            # #run7 OPS-D1A: bound the read. This is a general entry point that
            # can be pointed at an arbitrary directory; the capped-writer feeds it
            # normally, but an oversized (or maliciously large) *.sarif/*.json
            # would otherwise be slurped whole into memory. Read one byte past the
            # cap to detect the overflow, then fail-closed on that file.
            with open(path, "rb") as fh:
                raw = fh.read(MAX_TOOL_OUTPUT_BYTES + 1)
        except OSError as e:
            print("ingest skip %s: %s" % (path, e), file=sys.stderr)
            dispositions[tool] = {"status": "failed", "findings": 0,
                                  "reason": "unparseable: %s"
                                  % (str(e).splitlines() or [""])[0]}
            continue
        if len(raw) > MAX_TOOL_OUTPUT_BYTES:
            print("ingest skip %s: output exceeds the %d-byte cap"
                  % (path, MAX_TOOL_OUTPUT_BYTES), file=sys.stderr)
            dispositions[tool] = {"status": "failed", "findings": 0,
                                  "reason": "oversize: exceeds %d-byte cap"
                                  % MAX_TOOL_OUTPUT_BYTES}
            continue
        if not raw.strip():
            print("ingest skip %s: empty output file" % path, file=sys.stderr)
            dispositions[tool] = {"status": "failed", "findings": 0,
                                  "reason": "empty output file"}
            continue
        # Some tools decorate stdout before the JSON payload (calibration
        # 2026-08-03: bandit's progress bar corrupted its SARIF). Strip ANSI
        # escape sequences first — a CSI introducer '\x1b[' otherwise makes the
        # scan below trim to the '[' of the escape code rather than the real
        # JSON (pip-audit's progress spinner) — then trim to the first JSON
        # start token (object OR array; eslint emits a top-level array) so a
        # cosmetic prefix never discards real findings.
        raw = strip_ansi(raw)
        starts = [i for i in (raw.find(b"{"), raw.find(b"[")) if i != -1]
        first = min(starts) if starts else -1
        if first > 0:
            print("ingest note %s: stripped %d bytes of non-JSON prefix"
                  % (path, first), file=sys.stderr)
            raw = raw[first:]
        try:
            parsed = adapter.parse(raw, group)
        except Exception as e:  # noqa: BLE001 - tolerant by design
            print("ingest error %s: %s" % (path, e), file=sys.stderr)
            dispositions[tool] = {"status": "failed", "findings": 0,
                                  "reason": "unparseable: %s"
                                  % (str(e).splitlines() or [""])[0]}
            continue
        raw_count = len(parsed)
        parsed, fx_cnt, gl_cnt, ra_cnt = _filter_parsed_findings(
            parsed, include_fixtures, exclude_globs)
        fx_excluded += fx_cnt
        gl_excluded += gl_cnt
        ra_excluded += ra_cnt
        out.extend(parsed)
        dispositions[tool] = {"status": "ok" if raw_count else "empty",
                              "findings": raw_count}
    if fx_excluded or gl_excluded or ra_excluded:
        reasons = []
        if fx_excluded:
            reasons.append("test-fixture corpus")
        if ra_excluded:
            reasons.append("not project source (nested checkout / git dir / "
                           ".panopticon artifacts / generated bytecode / "
                           "vendored dependencies)")
        if gl_excluded:
            reasons.append(", ".join(exclude_globs))
        print("ingest: excluded %d finding(s) (%s)"
              % (fx_excluded + gl_excluded + ra_excluded, "; ".join(reasons)),
              file=sys.stderr)
    return out, dispositions


def ingest_dir(tools_dir, group, exclude_globs=None, include_fixtures=False):
    """Ingest raw tool-output files from a directory and route them to the
    registered adapter for parsing. Files without a registered adapter or that
    fail to parse are skipped with a stderr diagnostic.

    Findings-only wrapper over ingest_dir_detailed (unchanged contract).
    """
    findings, _dispositions = ingest_dir_detailed(
        tools_dir, group, exclude_globs, include_fixtures)
    return findings
